### ISSUE TITLE
Responsividade

### ISSUE THREAD

**Issue by marcos-nunes-dev** [marcos-nunes-dev/Grow-Roadmaps#10]
Preciso de ajudar para adaptação de responsividade. Como o layout é horizontal estou meio sem ideia de como ter um bom UX em mobile.

**Comment by YagoMatos** [comment]
Estava dando uma pesquisada, e talvez uma proposta bacana seria utilizar alguns conceitos e ideias do Bitbucket. Particularmente achei a arquitetura das informações um pouco parecidas.
